spring:
  application:
    name: NotificacionesJasper

url-pdf: /pdf/bindato

server:
  port: ${PORT_CARRITO:8086}
  address: 0.0.0.0
  servlet:
    context-path: /solicitud/resultado

info:
  status: UP

management:
  endpoints:
    web:
      base-path:
      
logging:
  level:
    org:
      hibernate:
        type: trace
        
BolivarException:
  codigo: ETBR01
  controller:
    mensaje: Error en generación de binDato
    errores:
      error1: Erro interno en Jasper. Generación de PDF
      
jasper:
  path_test1: src/main/resources/reports/demo_jasper_paises.jasper
  pathJasperSolicitud: src/main/resources/reports/J23ReporteResultados.jasper
  pathResult: src/main/resources/reports
  resultado:
    dato1: dato1
    dato2: dato2
    dato3: dato3
    dato4: dato4
    dato5: dato5
  parametros:
    inmobiliria: X_INMOBILIARIA
    agencia: X_AGENCIA
    direccion: X_DIRECCION
    fechaResultado: X_FECHARESULTADO
    canon: X_CANON
    admon: X_ADMON
    fecha: X_FECHA
